# Generated by Django 4.0.4 on 2022-06-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email_playlist_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
