# Generated by Django 4.0.4 on 2022-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_movie_playlist_alter_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='ispublic',
            field=models.BooleanField(default=False),
        ),
    ]
